<?php include('header.php'); ?>
<?php include('includes/slider-home.php'); ?>
<?php include('includes/services-first.php'); ?>
<?php include('includes/services-second.php'); ?>
<?php include('includes/services-third.php'); ?>
<?php include('includes/services-four.php'); ?>
<?php include('includes/services-seven.php'); ?>
<?php include('includes/services-packs.php'); ?>
<?php include('includes/services-coments.php'); ?>
<?php include('includes/services-six.php'); ?>
<?php include('includes/services-five.php'); ?>
<?php include('footer.php'); ?>
